/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Event;
import com.example.jooq.tables.Eventdate;
import com.example.jooq.tables.FlywaySchemaHistory;
import com.example.jooq.tables.Vote;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Eventschema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eventschema</code>
     */
    public static final Eventschema EVENTSCHEMA = new Eventschema();

    /**
     * The table <code>eventschema.event</code>.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * The table <code>eventschema.eventdate</code>.
     */
    public final Eventdate EVENTDATE = Eventdate.EVENTDATE;

    /**
     * The table <code>eventschema.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>eventschema.vote</code>.
     */
    public final Vote VOTE = Vote.VOTE;

    /**
     * No further instances allowed
     */
    private Eventschema() {
        super("eventschema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Event.EVENT,
            Eventdate.EVENTDATE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Vote.VOTE
        );
    }
}
