/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Eventdate implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long eventid;
    private final LocalDate date;
    private final Integer votes;

    public Eventdate(Eventdate value) {
        this.id = value.id;
        this.eventid = value.eventid;
        this.date = value.date;
        this.votes = value.votes;
    }

    public Eventdate(
        Long id,
        Long eventid,
        LocalDate date,
        Integer votes
    ) {
        this.id = id;
        this.eventid = eventid;
        this.date = date;
        this.votes = votes;
    }

    /**
     * Getter for <code>eventschema.eventdate.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>eventschema.eventdate.eventid</code>.
     */
    public Long getEventid() {
        return this.eventid;
    }

    /**
     * Getter for <code>eventschema.eventdate.date</code>.
     */
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Getter for <code>eventschema.eventdate.votes</code>.
     */
    public Integer getVotes() {
        return this.votes;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Eventdate other = (Eventdate) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.eventid == null) {
            if (other.eventid != null)
                return false;
        }
        else if (!this.eventid.equals(other.eventid))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        if (this.votes == null) {
            if (other.votes != null)
                return false;
        }
        else if (!this.votes.equals(other.votes))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventid == null) ? 0 : this.eventid.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.votes == null) ? 0 : this.votes.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Eventdate (");

        sb.append(id);
        sb.append(", ").append(eventid);
        sb.append(", ").append(date);
        sb.append(", ").append(votes);

        sb.append(")");
        return sb.toString();
    }
}
