/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Vote implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long dateid;
    private final String voter;

    public Vote(Vote value) {
        this.id = value.id;
        this.dateid = value.dateid;
        this.voter = value.voter;
    }

    public Vote(
        Long id,
        Long dateid,
        String voter
    ) {
        this.id = id;
        this.dateid = dateid;
        this.voter = voter;
    }

    /**
     * Getter for <code>eventschema.vote.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>eventschema.vote.dateid</code>.
     */
    public Long getDateid() {
        return this.dateid;
    }

    /**
     * Getter for <code>eventschema.vote.voter</code>.
     */
    public String getVoter() {
        return this.voter;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Vote other = (Vote) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.dateid == null) {
            if (other.dateid != null)
                return false;
        }
        else if (!this.dateid.equals(other.dateid))
            return false;
        if (this.voter == null) {
            if (other.voter != null)
                return false;
        }
        else if (!this.voter.equals(other.voter))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.dateid == null) ? 0 : this.dateid.hashCode());
        result = prime * result + ((this.voter == null) ? 0 : this.voter.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vote (");

        sb.append(id);
        sb.append(", ").append(dateid);
        sb.append(", ").append(voter);

        sb.append(")");
        return sb.toString();
    }
}
