/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Date;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DateRecord extends UpdatableRecordImpl<DateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.date.id</code>.
     */
    public DateRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.date.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.date.eventid</code>.
     */
    public DateRecord setEventid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.date.eventid</code>.
     */
    public Long getEventid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.date.date</code>.
     */
    public DateRecord setDate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.date.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.date.votes</code>.
     */
    public DateRecord setVotes(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.date.votes</code>.
     */
    public Integer getVotes() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DateRecord
     */
    public DateRecord() {
        super(Date.DATE);
    }

    /**
     * Create a detached, initialised DateRecord
     */
    public DateRecord(Long id, Long eventid, LocalDate date, Integer votes) {
        super(Date.DATE);

        setId(id);
        setEventid(eventid);
        setDate(date);
        setVotes(votes);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DateRecord
     */
    public DateRecord(com.example.jooq.tables.pojos.Date value) {
        super(Date.DATE);

        if (value != null) {
            setId(value.getId());
            setEventid(value.getEventid());
            setDate(value.getDate());
            setVotes(value.getVotes());
            resetChangedOnNotNull();
        }
    }
}
