/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Eventdate;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventdateRecord extends UpdatableRecordImpl<EventdateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eventschema.eventdate.id</code>.
     */
    public EventdateRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>eventschema.eventdate.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eventschema.eventdate.eventid</code>.
     */
    public EventdateRecord setEventid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>eventschema.eventdate.eventid</code>.
     */
    public Long getEventid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eventschema.eventdate.date</code>.
     */
    public EventdateRecord setDate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>eventschema.eventdate.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>eventschema.eventdate.votes</code>.
     */
    public EventdateRecord setVotes(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>eventschema.eventdate.votes</code>.
     */
    public Integer getVotes() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventdateRecord
     */
    public EventdateRecord() {
        super(Eventdate.EVENTDATE);
    }

    /**
     * Create a detached, initialised EventdateRecord
     */
    public EventdateRecord(Long id, Long eventid, LocalDate date, Integer votes) {
        super(Eventdate.EVENTDATE);

        setId(id);
        setEventid(eventid);
        setDate(date);
        setVotes(votes);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EventdateRecord
     */
    public EventdateRecord(com.example.jooq.tables.pojos.Eventdate value) {
        super(Eventdate.EVENTDATE);

        if (value != null) {
            setId(value.getId());
            setEventid(value.getEventid());
            setDate(value.getDate());
            setVotes(value.getVotes());
            resetChangedOnNotNull();
        }
    }
}
