/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Vote;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoteRecord extends UpdatableRecordImpl<VoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eventschema.vote.id</code>.
     */
    public VoteRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>eventschema.vote.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eventschema.vote.dateid</code>.
     */
    public VoteRecord setDateid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>eventschema.vote.dateid</code>.
     */
    public Long getDateid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eventschema.vote.voter</code>.
     */
    public VoteRecord setVoter(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>eventschema.vote.voter</code>.
     */
    public String getVoter() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoteRecord
     */
    public VoteRecord() {
        super(Vote.VOTE);
    }

    /**
     * Create a detached, initialised VoteRecord
     */
    public VoteRecord(Long id, Long dateid, String voter) {
        super(Vote.VOTE);

        setId(id);
        setDateid(dateid);
        setVoter(voter);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VoteRecord
     */
    public VoteRecord(com.example.jooq.tables.pojos.Vote value) {
        super(Vote.VOTE);

        if (value != null) {
            setId(value.getId());
            setDateid(value.getDateid());
            setVoter(value.getVoter());
            resetChangedOnNotNull();
        }
    }
}
