/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Eventschema;
import com.example.jooq.Keys;
import com.example.jooq.tables.records.EventdateRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Eventdate extends TableImpl<EventdateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eventschema.eventdate</code>
     */
    public static final Eventdate EVENTDATE = new Eventdate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventdateRecord> getRecordType() {
        return EventdateRecord.class;
    }

    /**
     * The column <code>eventschema.eventdate.id</code>.
     */
    public final TableField<EventdateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eventschema.eventdate.eventid</code>.
     */
    public final TableField<EventdateRecord, Long> EVENTID = createField(DSL.name("eventid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>eventschema.eventdate.date</code>.
     */
    public final TableField<EventdateRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>eventschema.eventdate.votes</code>.
     */
    public final TableField<EventdateRecord, Integer> VOTES = createField(DSL.name("votes"), SQLDataType.INTEGER, this, "");

    private Eventdate(Name alias, Table<EventdateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Eventdate(Name alias, Table<EventdateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eventschema.eventdate</code> table reference
     */
    public Eventdate(String alias) {
        this(DSL.name(alias), EVENTDATE);
    }

    /**
     * Create an aliased <code>eventschema.eventdate</code> table reference
     */
    public Eventdate(Name alias) {
        this(alias, EVENTDATE);
    }

    /**
     * Create a <code>eventschema.eventdate</code> table reference
     */
    public Eventdate() {
        this(DSL.name("eventdate"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eventschema.EVENTSCHEMA;
    }

    @Override
    public Identity<EventdateRecord, Long> getIdentity() {
        return (Identity<EventdateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EventdateRecord> getPrimaryKey() {
        return Keys.EVENTDATE_PKEY;
    }

    @Override
    public Eventdate as(String alias) {
        return new Eventdate(DSL.name(alias), this);
    }

    @Override
    public Eventdate as(Name alias) {
        return new Eventdate(alias, this);
    }

    @Override
    public Eventdate as(Table<?> alias) {
        return new Eventdate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Eventdate rename(String name) {
        return new Eventdate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Eventdate rename(Name name) {
        return new Eventdate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Eventdate rename(Table<?> name) {
        return new Eventdate(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Eventdate where(Condition condition) {
        return new Eventdate(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Eventdate where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Eventdate where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Eventdate where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Eventdate where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Eventdate where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Eventdate where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Eventdate where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Eventdate whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Eventdate whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
