/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Eventschema;
import com.example.jooq.Keys;
import com.example.jooq.tables.records.VoteRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Vote extends TableImpl<VoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eventschema.vote</code>
     */
    public static final Vote VOTE = new Vote();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VoteRecord> getRecordType() {
        return VoteRecord.class;
    }

    /**
     * The column <code>eventschema.vote.id</code>.
     */
    public final TableField<VoteRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eventschema.vote.dateid</code>.
     */
    public final TableField<VoteRecord, Long> DATEID = createField(DSL.name("dateid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>eventschema.vote.voter</code>.
     */
    public final TableField<VoteRecord, String> VOTER = createField(DSL.name("voter"), SQLDataType.VARCHAR, this, "");

    private Vote(Name alias, Table<VoteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Vote(Name alias, Table<VoteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eventschema.vote</code> table reference
     */
    public Vote(String alias) {
        this(DSL.name(alias), VOTE);
    }

    /**
     * Create an aliased <code>eventschema.vote</code> table reference
     */
    public Vote(Name alias) {
        this(alias, VOTE);
    }

    /**
     * Create a <code>eventschema.vote</code> table reference
     */
    public Vote() {
        this(DSL.name("vote"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eventschema.EVENTSCHEMA;
    }

    @Override
    public Identity<VoteRecord, Long> getIdentity() {
        return (Identity<VoteRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VoteRecord> getPrimaryKey() {
        return Keys.VOTE_PKEY;
    }

    @Override
    public Vote as(String alias) {
        return new Vote(DSL.name(alias), this);
    }

    @Override
    public Vote as(Name alias) {
        return new Vote(alias, this);
    }

    @Override
    public Vote as(Table<?> alias) {
        return new Vote(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Vote rename(String name) {
        return new Vote(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vote rename(Name name) {
        return new Vote(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vote rename(Table<?> name) {
        return new Vote(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Condition condition) {
        return new Vote(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
